comlink.ts
Comlink is amazing. It would be even more amazing if it could detect transferable types automatically, and while attempting to make it do that I stumbled onto a performance gain.
Assuming `value` is a `TypedArray` instance, `Object.keys` will include the numeric indexes, which the existing code then iterates over. A 2mb `Uint8Array`, for example, results in 2 million unnecessary iterations. This change avoids those iterations AND lets you do stuff like `proxyThing.doStuff(myTypedArrayInstance)` and get buffer transfers for free. In my ad hoc testing this reduces the time it takes to send a 2mb buffer from 3.5 seconds to about 6ms.
=> Faster, automatic handling of TypedArray instances

comlink.ts
It looks like the redundant call for entries() fails on some browsers.
I encountered a problem when using a Babel with runtime transform. It transformed
```
for... of map.entries()
```
into
```
... map.entries()[Symbol.iterator]
```
which results with an error, at least on older Android API 23.
=> Fix for...of transferHandlers loops syntax (omit .entries())

comlink.ts
This fix allows calling both `expose` and `proxy` for the same endpoint.
The attached message handler for `expose` should ignore messages without a `callPath` key in `event.data.msg`.
=> Ignore events without msg.callPath key in exposed message handler

comlink.ts, tests/same_window.comlink.test.js
Allow `Comlink.proxy` to be called with `callPath` and `target` parameters, so it can be used with [GoogleChrome/proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill) when native ES6 Proxy is unavailable.
Disclaimer: I have no experience with TypeScript or Karma. I hope that I used them properly :)
=> Make Comlink compatible with GoogleChrome/proxy-polyfill

messagechanneladapter.ts
Silently ignore string messages which can't be parsed as a json.
This shouldn't happen if only Comlink uses the smc. However, if some other module uses it, it might happen. 
I encountered this error in a React-Native app,  where I received an empty message `{data: ""}` due to some random React-Native bug. In this case, it causes the app to crash.
=> Wrap JSON.parse with a try...catch block.

README.md
Maybe I got it all wrong, but to me the following two quotes from the readme seem to contradict themselves:
```
If you invoke function, all parameters will be structurally cloned or transferred if they are transferable.
```
```
By default, all parameters to a function are copied (structural clone):
```
I adapted the readme which hopefully fixes the contradiction. If not, please clear up my confusion which would ensue otherwise :)
=> Update readme to reflect that transferable function parameters are not structurally copied by default

comlink.ts
This should fix the `Cannot find name 'Window'` error.
=> Reference lib.dom.d.ts for Window type, fixes #123

Dockerfile, comlink.ts, dist/comlink.d.ts, dist/comlink.js, dist/umd/comlink.d.ts, dist/umd/comlink.js, package-lock.json, package.json, tests/same_window.comlink.test.js, tests/tsconfig.json, tests/types.ts, tsconfig.json, tslint.json
Closes #203 
This makes it so that the `Comlink.proxy()` return type does not Promisify properties that were wrapped by `Comlink.proxyValue()`.
This allows type-safe nested method calls and property accesses of proxies objects.
To accomplish this, it exposes the `proxyValue` symbol to the type system so that the `Comlink.proxy()` return type can type switch on its presence.
To prevent regressions of the types, this adds tests for the types with dtslint.
I also added two runtime unit tests that verify the runtime behaviour.
=> Typesafe nested method calls

dist/messagechanneladapter.js, dist/umd/messagechanneladapter.js, mangle_umd.js, messagechanneladapter.ts, tests/messagechanneladapter.test.js
- fix a MessageChannelAdapter issue that pingPongMessage failed to receive response on on top level channel if `wrap()` without an id
- update mangle_umd script to let MessageChannelAdapter exports to window.MessageChannelAdapter
=> fix MessageChannelAdapter issue

comlink.ts, dist/comlink.js, dist/umd/comlink.js, tests/same_window.comlink.test.js
TypedArray.prototype.buffer is ArrayBuffer, so it is Transferable.
However, because of `iterateAllProperties` skips TypedArray, TypedArray.prototype.buffer won't be detected as Transferable.
This PR enable to detect Transferable in TypedArray.
=> Detect TypedArray.buffer is Transferable

rollup.config.js, tests/same_window.comlink.test.js
Array.prototype.flat isn't available in Node 10. Use alternative old API for the same purpose.
=> use alternative API to allow build via Node 10

src/comlink.ts
I think this is fix to somewhat specific usecases, but hope this is not hurting general environments but also fixes my problem.
In our application we use comlink to communicate between the different context in Electron (https://electronjs.org/), specifically for now being used between `preload` script to actual web page we load into BrowserWindow. Since we inject script in preload it does not have url for endpoint while our endpoint have CSP policy to prevent execution of script via `eval` or similar way - and using `new Function()` violates those rules.
And effectively blocks to create new proxy object in preload context we created. 
This PR replaces creation of function in non-eval way to allow preload script can run under specific CSP policy.
=> fix(createproxy): allow proxy under non-eval csp

src/comlink.ts, src/protocol.ts
TypeScript comes with a [built-in type definition](https://github.com/microsoft/TypeScript/blob/v3.4.5/lib/lib.dom.d.ts#L18304) for [transferable objects](https://developer.mozilla.org/en-US/docs/Web/API/Transferable). Let's use it! 🙂
This changes the following types in Comlink's public API (`dist/umd/comlink.d.ts`):
```diff
export interface TransferHandler {
canHandle(obj: any): boolean;
-    serialize(obj: any): [any, any[]];
+    serialize(obj: any): [any, Transferable[]];
deserialize(obj: any): any;
}
-export declare function transfer(obj: any, transfers: any[]): any;
+export declare function transfer(obj: any, transfers: Transferable[]): any;
```
=> Use Transferable type

src/comlink.ts, src/protocol.ts
If comlink is used with typescript, where only compilerOptions.lib "webworker" without "dom"
is configured, the error "Cannot find name 'Window'" is thrown. This PR replaces the Window
type with a custom types that declare the minimal required functionality to work.
=> fix: replace Window type with reduced types

src/comlink.ts, src/protocol.ts, tests/same_window.comlink.test.js
This PR provides a fix for memory leak discussed in https://github.com/GoogleChromeLabs/comlink/issues/63
The fix here provides a method 'releaseProxy' on the object return by createProxy. This allows the consumer of the proxy to indicate when they are done using the proxy and free up held refs and close the message ports on both ends. If proxy is subsequently used an exception will be thrown.
As discussed with @surma this PR provides a temporary fix until WeakRefs are widely supported, then comlink will be able to properly address issue and this PR will be obsolete.
To use with leaking test in issue #63 the test function in app.ts would be changed to:
```
async function test()
{
const app = await new App();
const returned = await app.getObject();
await returned.work();
// stop memory …
```
=> Temp memory leak fix

src/comlink.ts, tests/same_window.comlink.test.js
Hi there,
Right now comlink doesn't work with proxy-polyfill. This is because **proxy-polyfill** seals the object when creates the proxy and properties can't be added afterwards and **comlink** wrap function always creates the Proxy with an empty function as target.
I've checked project history and this was once addressed ( in this PR 
https://github.com/GoogleChromeLabs/comlink/pull/113/files ) but somehow changes were lost after a big update. 
It's a very little change, Do you think is possible to add it again? I have tested using comlink with proxy-polyfills on IE11 and it just works :)
PS. I'm not very familiar with TS, let me know if I missed something.
Thanks!
=> Expose target to make comlink compatible  with proxy-polyfill

package.json, src/comlink.ts, tests/tsconfig.json, tests/type-checks.ts, tsconfig.json
This fixes the typings issues described in #432.
- `Promisify<T>` needs to check first whether `T extends Promise` already. Otherwise it could resolve to `Promise<Promise<T>>` if `T` already is a Promise  (which is impossible in comlink and JavaScript in general).
- In the mapped types, each right side generally needs to be extracted into its own type alias. This is because generic type aliases will distribute over union types, while inlining the type would not. This means the type would not work properly when union types are involved. This may sound like an edge case, but includes e.g. optional properties, which are union types `xxx | undefined`.
- (most complicated part) For proxied functions, while the return type needs to be wrapped in `Remote<T>`, the parameters of the functions need …
=> Fix TypeScript types

src/comlink.ts, src/protocol.ts, tests/same_window.comlink.test.js, tests/type-checks.ts
This is a simple improvement to make transfer handlers type-safe instead of using `any`. This allows all types to be inferred (see the tests) and I think it also helps communicating how they work. It would also help in informing users when the API changes - e.g. I missed that from v3 to v4 the interface of `serialize()` was changed to return a tuple because it was typed `any`.
The deserialized type is required to be the same as the input because otherwise it would be impossible to type basically anything about proxied objects, so this ensures an important invariant. The internal proxy transfer handler technically has a different return type, but because it is internal we can consider it in the typings, which we cannot do with user transfer handlers. This is generally how people would use …
=> Improve transfer handler typings

tests/type-checks.ts
Fixes #471
It seems that when the return from `comlink.proxy()` is directly returned, there is a problem with type inference where the compiler does not infer the right type. Maybe it triggers some usage-based inference that is invalid in this scenario. When assigning it first to a variable, the type is inferred correctly for the variable, and then returning that variable works.
We were actually doing the same workaround in the test for the synchronous case, which exhibits the same problem. But for some reason the issue wasn't present when using an `async` function, but is now as of `v3.9.3`.
@DanielRosenwasser do you have any idea what's going on here? Should this be filed as a bug in TypeScript?
=> Fix disabled test

package.json
Importing comlink does not have any side effects. However, bundlers like Rollup are unable to determine this because `comlink.ts` instantiates a Map and a WeakMap:
https://github.com/GoogleChromeLabs/comlink/blob/c69224eb4e33076df68d7ac8ed14be2cff7a3962/src/comlink.ts#L276
https://github.com/GoogleChromeLabs/comlink/blob/c69224eb4e33076df68d7ac8ed14be2cff7a3962/src/comlink.ts#L470
By adding `sideEffects: false` to `package.json`, Comlink will indicate to bundlers that they can safely drop the Comlink import if none of the exports are used.
For example, Rollup will read the `sideEffects` value in the `node-resolve` plugin here: https://github.com/rollup/plugins/blob/867c69990a27ee234a4babdf2dd24151cd4d5e55/packages/node-resolve/src/util.js#L138-L140
=> Mark comlink as not having side effects

src/string-channel.experimental.ts, tests/string-channel.test.js
I know this is just experimental, but it might help for someone like me.
Callbacks weren't working.
* added added fix for it (calling .start() on wrapped MessagePort)
* added a test to prove it's working now
=> Fixed string-channel to work with callbacks

src/comlink.ts, tests/cross-origin.comlink.test.js, tests/fixtures/attack-iframe.html
Partial fix for #603 allowing a user to specify an origin filtering regexp/string array to control which origins comlink will listen to.
Not sure if a full fix for #603 would require prevention of prototype changes, but I feel like if you `expose` on window you're always going to be a bit vulnerable unless you specify a filtering origin.
=> Add origin filtering for expose

README.md
Fixes #606 by adding basic docs for `expose` functions new `allowedOrigins` array argument.
=> Adds docs for expose allowedOrigins parameter

src/comlink.ts, src/node-adapter.ts, src/protocol.ts
This PR changes the license headers on the `.ts` source files in the following ways:
1. Adds a `@license` annotation, so that tools like Terser and Closure compiler will automatically know to preserve these license headers by default.
2. Uses a new, more concise style of header with the `SPDX-License-Identifier` property, which is approved by Google's open source office (e.g. it's [used by Lit](https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts)).
=> Use shorter SPDX @license headers

.husky/pre-commit, package.json, rollup.config.mjs, src/comlink.ts, tsconfig.json
We have a number of PRs open from renovate bot prompting some updates to dependencies, many of which are several major versions out of date now. This PR upgrades them all.
Should close the following PRs #488, #494, #498, #517, #527, #535, #536, #582
Also fixes one small type issue that arose with the upgrade to TS.
=> Upgrades numerous dependencies

src/comlink.ts, tests/same_window.comlink.test.js
When an unserializable type is returned such as a function, this results in an uncaught error. In Deno, this crashes the application. This change catches the error and returns a serialized error type so that it can be handled by the calling thread.
According to the MDN, there are currently two types of objects that do not work with the structured clone algorithm and will result in a DataCloneError: "a function" and "a DOM node".
=> Unserializable return type error

src/comlink.ts
This is to fix runtime errors that occur when Comlink is used in a `Worklet` because `self` doesn't exist there.
I ran into a problem suddenly using Comlink in an `AudioWorklet` getting runtime errors [on line 425 because it's looking for the existence of a property on the `self` object](https://github.com/GoogleChromeLabs/comlink/blob/fd7330f7721182c068e988cea27370e72ca26d16/src/comlink.ts#L425)  -- since `self` isn't available in `Worklet`s I just replaced it with `globalThis` and it resolved the issue.
(The suddenness of it was just an unrelated tree-shaking issue -- if `expose` is optimized out by whatever bundler you're using then the `Worklet` never inspects `self`, and never crashes. It's possible that this issue could suddenly affect others if they change how they use Comlink in …
=> Replace `self` with `globalThis` for use in Worklets

src/comlink.ts
From #649:
> We make heavy use of Comlink for our WebWorker communication. On some recent profiling traces I noticed a hot-path on the "addEventListener" line.
>
> <img width="678" alt="292389350-2052be72-8671-4e20-9e06-fef0a30cb420" src="https://github.com/GoogleChromeLabs/comlink/assets/9250155/06276f85-086f-4e4f-b1a9-ecaa07e38ceb">
>
> While its hard to say exactly how the event listeners are stored, most implementations I've seen for such interfaces involve storing them in an array and removing the listener equally requires adjusting an array. The existing logic also creates two closures - one for the Promise (which is unavoidable from what I can tell), and another for the event listener. As it was suggested in https://github.com/GoogleChromeLabs/comlink/issues/647 there is a …
=> Use a single "message" event listener to dispatch received messages
